CC = gcc
CFLAGS = -lglut -lGLU -lGL -lm

hw: hw3-4-a.c hw3-4-b.c hw3-4-c.c hw3-5.c
	$(CC) hw3-4-a.c $(CFLAGS) -o hw3-4-a
	$(CC) hw3-4-b.c $(CFLAGS) -o hw3-4-b
	$(CC) hw3-4-c.c $(CFLAGS) -o hw3-4-c
	$(CC) hw3-5.c $(CFLAGS) -o hw3-5
