CC = gcc
CFLAGS = -lglut -lGLU -lGL -lm

hw: hw1-3.c hw1-4.c hw1-5.c hw1-5-a.c hw1-5-b.c hw1-5-c.c Schlafli1.c Schlafli2.c
	$(CC) hw1-3.c $(CFLAGS) -o hw1-3
	$(CC) hw1-4.c $(CFLAGS) -o hw1-4
	$(CC) hw1-5.c $(CFLAGS) -o hw1-5
	$(CC) hw1-5-a.c $(CFLAGS) -o hw1-5-a
	$(CC) hw1-5-b.c $(CFLAGS) -o hw1-5-b
	$(CC) hw1-5-c.c $(CFLAGS) -o hw1-5-c
	$(CC) Schlafli1.c $(CFLAGS) -o Schlafli1
	$(CC) Schlafli2.c $(CFLAGS) -o Schlafli2
