CC = gcc
CFLAGS = -lglut -lGLU -lGL -lm

ex:
	$(CC) clock.c $(CFLAGS) -o clock
	$(CC) ex01.c $(CFLAGS) -o ex01
	$(CC) ex02.c $(CFLAGS) -o ex02
	$(CC) ex03.c $(CFLAGS) -o ex03
	$(CC) ex04.c $(CFLAGS) -o ex04
	$(CC) ex05.c $(CFLAGS) -o ex05
	$(CC) ex06.c $(CFLAGS) -o ex06
	$(CC) ex07.c $(CFLAGS) -o ex07
	$(CC) ex08-a.c $(CFLAGS) -o ex08-a
	$(CC) ex08-b.c $(CFLAGS) -o ex08-b
	$(CC) ex09.c $(CFLAGS) -o ex09
	$(CC) ex10.c $(CFLAGS) -o ex10
	$(CC) ex11.c $(CFLAGS) -o ex11
	$(CC) ex12.c $(CFLAGS) -o ex12
	$(CC) ex13.c $(CFLAGS) -o ex13
	$(CC) ex14.c $(CFLAGS) -o ex14
	$(CC) ex15.c $(CFLAGS) -o ex15
	$(CC) ex16.c $(CFLAGS) -o ex16
	$(CC) ex17.c $(CFLAGS) -o ex17
	$(CC) ex18.c $(CFLAGS) -o ex18
	$(CC) ex19-a.c $(CFLAGS) -o ex19-a
	$(CC) ex19-b.c $(CFLAGS) -o ex19-b
	$(CC) ex20.c $(CFLAGS) -o ex20
	$(CC) ex21.c $(CFLAGS) -o ex21
	$(CC) ex22-a.c vect.c $(CFLAGS) -o ex22-a
	$(CC) ex22-b.c vect.c $(CFLAGS) -o ex22-b
	$(CC) ex22-c.c vect.c $(CFLAGS) -o ex22-c

ex04:ex04.c
	$(CC) ex04.c $(CFLAGS) -o ex04
